version: '2'

services:
  rabbitmq:
    image: 'docker.io/bitnami/rabbitmq:latest'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    environment:
      - 'RABBITMQ_USERNAME=joergen'
      - 'RABBITMQ_PASSWORD=joergen'
volumes:
  rabbitmq_data:
    driver: local
